name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push app Image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: |
            neelp03/app:latest
            neelp03/app:${{ github.sha }}

      - name: Build and Push data_generator Image
        uses: docker/build-push-action@v4
        with:
          context: ./data_generator
          push: true
          tags: |
            neelp03/data_generator:latest
            neelp03/data_generator:${{ github.sha }}

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            cd /root/deployment
            docker compose pull
            docker compose up -d
